// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Placeholder for user-supplied values.
values: {
    commonGroups: {
        mysql: {
            host: "127.0.0.1"
            port: 1234
            user: "admin"
            password: "secret"
        }
        redis: {
            host: "127.0.0.1"
            port: 1235
        }
        s3: {
            host: "aws.com"
            port: 443
            region: "eu-west1"
        }
    }

    service1:
        redis: {
            host: "redis-local.com"
            port: 135
        }

    service2:
        mysql: {
            user: "admin_svc2"
            password: "secret2"
        }
    service3: {
        redis: {
            host: "redis.com"
        }

        mysql: {
            user: "admin_svc3"
            password: "secret3"
        }
    }
}
